#include "nesl_rtw_swl.h"
#include "ssc_ml_fun.h"
#include "Microgrid_with_Utility_Connection_d0b73514_0_external_struct.h"
#include "Microgrid_with_Utility_Connection_d0b73514_0_externals.h"
#include "Microgrid_with_Utility_Connection_d0b73514_0_gmt.h"
#include "Microgrid_with_Utility_Connection_d0b73514_0_slc_0.h"
#include "Microgrid_with_Utility_Connection_d0b73514_0_slc_1.h"
#include "Microgrid_with_Utility_Connection_d0b73514_0_slc_2.h"
#include "Microgrid_with_Utility_Connection_d0b73514_0_slc_3.h"
#include "Microgrid_with_Utility_Connection_d0b73514_0_slc_4.h"
#include "Microgrid_with_Utility_Connection_d0b73514_0_slc_5.h"
#include "Microgrid_with_Utility_Connection_d0b73514_0_slc_6.h"
#include "Microgrid_with_Utility_Connection_d0b73514_0_slc_7.h"
#include "Microgrid_with_Utility_Connection_d0b73514_0_slc_8.h"
#include "Microgrid_with_Utility_Connection_d0b73514_0_dc.h"
#include "Microgrid_with_Utility_Connection_d0b73514_0_initer.h"
static void sls_destroy ( SwitchedLinearSystem * sls ) { ( void ) sls ; }
SwitchedLinearSystem * Microgrid_with_Utility_Connection_d0b73514_0 ( PmAllocator * allocator ) { static int32_T diff_indices_ [ 7 ] = { 12 , 13 , 14 , 15 , 16 , 7 , 8 } ; static PmIntVector diff_indices = { 7U , diff_indices_ } ; static NeDynamicSystemInputSizes sizes = { { 2U , 82U , 1U , 7U , 0U , 33U , 0U , 0U , 0U , 4U , 0U , 1U , 0U , 0U , 0U , 2U , 0U , 0U , 0U , 2U , } } ; static SwitchedLinearClump * clumps [ 9U ] ; static SwitchedLinearSystem sls ; static NeModelParameters modelparams ; static NeSolverParameters solverparams ; solverparams = * ( ( ( NeSolverParameters * * ) allocator ) [ 0 ] ) ; modelparams = * ( ( NeModelParameters * ) ( ( ( NeSolverParameters * * ) allocator ) [ 1 ] ) ) ; sls . mSizes = sizes ; sls . mDiffStateIndices = & diff_indices ; sls . mGlobalMethodTable = Microgrid_with_Utility_Connection_d0b73514_0_gmt ( NULL ) ; sls . mNumClumps = 9U ; sls . mClumps = clumps ; sls . mClumps [ 0U ] = Microgrid_with_Utility_Connection_d0b73514_0_slc_0 ( NULL ) ; sls . mClumps [ 1U ] = Microgrid_with_Utility_Connection_d0b73514_0_slc_1 ( NULL ) ; sls . mClumps [ 2U ] = Microgrid_with_Utility_Connection_d0b73514_0_slc_2 ( NULL ) ; sls . mClumps [ 3U ] = Microgrid_with_Utility_Connection_d0b73514_0_slc_3 ( NULL ) ; sls . mClumps [ 4U ] = Microgrid_with_Utility_Connection_d0b73514_0_slc_4 ( NULL ) ; sls . mClumps [ 5U ] = Microgrid_with_Utility_Connection_d0b73514_0_slc_5 ( NULL ) ; sls . mClumps [ 6U ] = Microgrid_with_Utility_Connection_d0b73514_0_slc_6 ( NULL ) ; sls . mClumps [ 7U ] = Microgrid_with_Utility_Connection_d0b73514_0_slc_7 ( NULL ) ; sls . mClumps [ 8U ] = Microgrid_with_Utility_Connection_d0b73514_0_slc_8 ( NULL ) ; sls . mDiffClump = Microgrid_with_Utility_Connection_d0b73514_0_dc ( NULL ) ; sls . mIniter = Microgrid_with_Utility_Connection_d0b73514_0_initer ( & modelparams , & solverparams ) ; sls . mDaeIniter = NULL ; sls . mDestroy = sls_destroy ; sls . mGetNDPermData = NULL ; return & sls ; }
