#include "nesl_rtw_swl.h"
#include "ssc_ml_fun.h"
#include "Microgrid_with_Utility_Connection_b6e50c02_0_external_struct.h"
#include "Microgrid_with_Utility_Connection_b6e50c02_0_externals.h"
#include "Microgrid_with_Utility_Connection_b6e50c02_0_gmt.h"
#include "Microgrid_with_Utility_Connection_b6e50c02_0_slc_0.h"
#include "Microgrid_with_Utility_Connection_b6e50c02_0_slc_1.h"
#include "Microgrid_with_Utility_Connection_b6e50c02_0_slc_2.h"
#include "Microgrid_with_Utility_Connection_b6e50c02_0_slc_3.h"
#include "Microgrid_with_Utility_Connection_b6e50c02_0_slc_4.h"
#include "Microgrid_with_Utility_Connection_b6e50c02_0_slc_5.h"
#include "Microgrid_with_Utility_Connection_b6e50c02_0_slc_6.h"
#include "Microgrid_with_Utility_Connection_b6e50c02_0_slc_7.h"
#include "Microgrid_with_Utility_Connection_b6e50c02_0_slc_8.h"
#include "Microgrid_with_Utility_Connection_b6e50c02_0_slc_9.h"
#include "Microgrid_with_Utility_Connection_b6e50c02_0_slc_10.h"
#include "Microgrid_with_Utility_Connection_b6e50c02_0_slc_11.h"
#include "Microgrid_with_Utility_Connection_b6e50c02_0_dc.h"
#include "Microgrid_with_Utility_Connection_b6e50c02_0_initer.h"
static void sls_destroy ( SwitchedLinearSystem * sls ) { ( void ) sls ; }
SwitchedLinearSystem * Microgrid_with_Utility_Connection_b6e50c02_0 ( PmAllocator * allocator ) { static int32_T diff_indices_ [ 20 ] = { 0 , 1 , 2 , 84 , 62 , 76 , 82 , 46 , 54 , 32 , 78 , 81 , 83 , 31 , 53 , 52 , 55 , 44 , 49 , 30 } ; static PmIntVector diff_indices = { 20U , diff_indices_ } ; static NeDynamicSystemInputSizes sizes = { { 16U , 153U , 1U , 14U , 0U , 85U , 0U , 0U , 0U , 210U , 0U , 1U , 0U , 0U , 0U , 0U , 0U , 0U , 0U , 0U , } } ; static SwitchedLinearClump * clumps [ 12U ] ; static SwitchedLinearSystem sls ; static NeModelParameters modelparams ; static NeSolverParameters solverparams ; solverparams = * ( ( ( NeSolverParameters * * ) allocator ) [ 0 ] ) ; modelparams = * ( ( NeModelParameters * ) ( ( ( NeSolverParameters * * ) allocator ) [ 1 ] ) ) ; sls . mSizes = sizes ; sls . mDiffStateIndices = & diff_indices ; sls . mGlobalMethodTable = Microgrid_with_Utility_Connection_b6e50c02_0_gmt ( NULL ) ; sls . mNumClumps = 12U ; sls . mClumps = clumps ; sls . mClumps [ 0U ] = Microgrid_with_Utility_Connection_b6e50c02_0_slc_0 ( NULL ) ; sls . mClumps [ 1U ] = Microgrid_with_Utility_Connection_b6e50c02_0_slc_1 ( NULL ) ; sls . mClumps [ 2U ] = Microgrid_with_Utility_Connection_b6e50c02_0_slc_2 ( NULL ) ; sls . mClumps [ 3U ] = Microgrid_with_Utility_Connection_b6e50c02_0_slc_3 ( NULL ) ; sls . mClumps [ 4U ] = Microgrid_with_Utility_Connection_b6e50c02_0_slc_4 ( NULL ) ; sls . mClumps [ 5U ] = Microgrid_with_Utility_Connection_b6e50c02_0_slc_5 ( NULL ) ; sls . mClumps [ 6U ] = Microgrid_with_Utility_Connection_b6e50c02_0_slc_6 ( NULL ) ; sls . mClumps [ 7U ] = Microgrid_with_Utility_Connection_b6e50c02_0_slc_7 ( NULL ) ; sls . mClumps [ 8U ] = Microgrid_with_Utility_Connection_b6e50c02_0_slc_8 ( NULL ) ; sls . mClumps [ 9U ] = Microgrid_with_Utility_Connection_b6e50c02_0_slc_9 ( NULL ) ; sls . mClumps [ 10U ] = Microgrid_with_Utility_Connection_b6e50c02_0_slc_10 ( NULL ) ; sls . mClumps [ 11U ] = Microgrid_with_Utility_Connection_b6e50c02_0_slc_11 ( NULL ) ; sls . mDiffClump = Microgrid_with_Utility_Connection_b6e50c02_0_dc ( NULL ) ; sls . mIniter = Microgrid_with_Utility_Connection_b6e50c02_0_initer ( & modelparams , & solverparams ) ; sls . mDaeIniter = NULL ; sls . mDestroy = sls_destroy ; sls . mGetNDPermData = NULL ; return & sls ; }
